apiVersion: v1
kind: Route
metadata:
  labels:
    name: eparis-kibana
  name: eparis-kibana
spec:
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: eparis-kibana-logging
